### ISSUE TITLE
Shader error in 'Hidden/Graphics Tools/DebugMipColor': 'GetDebugMipColor': cannot implicitly convert from 'float4' to 'Texture2D<float4>' at line 71 (on d3d11)

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedReality-GraphicsTools-Unity#128]
## Describe the bug

On a full reimport, I'm getting this shader error:

<img width="491" alt="image" src="https://user-images.githubusercontent.com/3580640/206558828-3cd47bec-3ade-4226-968d-df6491f5902a.png">

## To reproduce

Using Graphics Tools 0.4.0
Using Unity 2020.3.42f1

1. Import Graphics Tool 0.4.0
2. Not sure if this will show up on first import
3. If it doesn't, right click on any asset and click "Reimport All"

**Comment by Cameron-Micka** [comment]
Thanks @keveleigh! Looks like this was fixed in #42. Please feel free to re-open this if it still occurs in [0.4.17](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/releases/tag/v0.4.17) and above.

**Comment by keveleigh** [comment]
Oh thanks! I'll definitely upgrade our project and take a look.
