### ISSUE TITLE
Add Headers to Autogenerated Classes

### ISSUE THREAD

**Issue by JPalmerDev** [microsoft/MixedReality-GraphicsTools-Unity#132]
## Overview
Various components are made with autogenerated scripts to mirror shader properties.
These can create stacks of similar names with low readability.
![image](https://user-images.githubusercontent.com/53239030/207723495-c6fcea65-856d-4d4a-bb76-362edef814ee.png)

It'd be good if there were some headers put in here.
Cameron mentioned that headers exist in other files, and those could possibly be scraped and Unity editor Headers() could be added.

CanvasMaterialAnimatorCanvasFrontplate.cs

## Expected behavior
Name aspects separated by meaningful headers

## Actual behavior
No headers, just lots of fields in a row, increasing the time it takes to read and look for certain parameters to tweak.

## Steps to reproduce
Look at the inspector.

## Unity editor version
Any

## Graphics Tools release version
0.4.15

**Comment by Cameron-Micka** [comment]
Unity has syntax in their ShaderLab for automatically adding headers to a materials inspector that looks like this: 
![image](https://user-images.githubusercontent.com/13305729/213496674-cc830530-a5f3-44a5-a693-f675d5a9b201.png)
Source: https://docs.unity3d.com/ScriptReference/MaterialPropertyDrawer.html

Unity also has a header attribute for displaying properties in the Unity inspector that look like this:
![image](https://user-images.githubusercontent.com/13305729/213496944-0517a587-1236-46ee-b838-096d7f8c4f39.png)
Source: https://docs.unity3d.com/ScriptReference/HeaderAttribute.html

The ShaderLab and C# headers both present a similar result in the Unity inspector which leads us to the ask for this task.

Right now, all autogenerated [animation components](https://learn.microsoft.com/en-us/windows/mixed-reality/mrtk-unity/mrtk3-graphicstools/features/animation) are created with the following code: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/blob/9f4e35db81b680060d70609e61a47e0efddba1de/com.microsoft.mrtk.graphicstools.unity/Editor/Utilities/ShaderUtilities.cs#L83

The ask is if the shader contains a header attribute in the ShaderLab code that the same header be transposed to the generated C# class.
