### ISSUE TITLE
Thqnk

### ISSUE THREAD

**Issue by Teezbrowdy** [microsoft/MixedReality-GraphicsTools-Unity#145]
## Your setup (please complete the following information)

- Unity Version [e.g. 2021.3.3f1]
- Graphics Tools Version [e.g. v0.4.0]

## Target platform (please complete the following information)

- HoloLens 2
- Standalone PC
- etc.

**Comment by Cameron-Micka** [comment]
Hi @Teezbrowdy, thanks for opening this issue. I don't see any content in the issue so I'm going to close it for now. But please feel free to open a new issue.
