### ISSUE TITLE
I feel it would be useful if GraphicsToolsShader's Emmision had an EmmisionMap function.

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedReality-GraphicsTools-Unity#19]
## Describe the problem

GraphicsToolsShader has many functions and is very attractive, but it does not currently have an emission map, which many shaders with emission functions, such as URP/LitShader, have.

<img width="1378" alt="untitleds2" src="https://user-images.githubusercontent.com/36409613/173230612-3e341761-bb95-4a4c-9c44-4b8ea0f016d0.png">

　I feel that the availability of EmmittionMap allows for more complex and attractive graphics.
　In fact, with the use of external resources such as Holographic Remoting and Azure RemoteRendering, as well as PCVR, HoloLens 2 apps can now use very high definition graphics.　I found myself wishing for EmissionMap when using emission for these applications.

　However, if EmmittionMap is not intentionally employed, please teach me know. (load, etc.?)
 　currently using ChannelMap to manage this, but we think it would be useful to have EmmittionMap.

## Describe the solution you'd like

I want to incorporate an Emmittion Map into Graphics/StandardShader.

Specifically, in GraphicsToolsStandardProgram.hlsl, per line 400 can be implemented by processing the EmissionMap following .

````
    half3 emission = GTsRGBToLinear(_EmissiveColor.rgb);
   ///emitton Map Process
````

However, GraphicsTools/StandardShader is managed by "Microsoft.MixedReality.GraphicsTools.Editor.StandardShaderGUI". StandardShaderGUI". I need understand this .

　If this proposal is approved, I will incorporate the functionality and publish a PR while also learning GraphicsTools.

**Comment by Cameron-Micka** [comment]
This is a great suggestion, thank you @HoloMoto! We will add this to our task list.

**Comment by HoloMoto** [comment]
Thank you very much. @Cameron-Micka 
I will get to work on it over the this weekend!

**Comment by HoloMoto** [comment]
@Cameron-Micka 
challenging.
https://github.com/HoloMoto/MixedReality-GraphicsTools-Unity/tree/holomoto/emissionmap

I added an EmissionMap to show the image properties in the inspector when Emission is enabled, and I added a process to multiply the emissionColor in the Shader.
It is working well in URP.

![2022-06-04 173854](https://user-images.githubusercontent.com/36409613/174516312-8ec1af97-dee5-46a8-829a-0ec83c6effd7.png)

However, the build-in throws an error.


Specifically, it appears to be a syntax error in tex2D.
```
//GraphicsToolsStandardProgram.hlsl Line 496~475 
#if defined(_EMISSION)
#if defined(_URP)
    half3 emissionMap = SAMPLE_TEXTURE2D(_EmissiveMap, sampler_EmissiveMap, input.uv);
#else
    half3 emissionMap = tex2D(_EmissiveMap, input.uv);
#endif
#endif
````
To find out what is wrong, I wrote the following as a test.

```
half3 emissionMap = tex2D(_MainTex, input.uv);
```
I copied the albedo defined just before line.
　But this still gives the same error.
```
Shader error in 'Graphics Tools/Standard': 'tex2D': no matching 2 parameter intrinsic function; Possible intrinsic functions are: tex2D(sampler2D, float2|half2|min10float2|min16float2) tex2D(sampler2D, float2|half2|min10float2|min16float2, float2|half2|min10float2|min16float2, float2|half2|min10float2|min16float2) at /UnityProject/MixedReality-GraphicsTools-Unity/com.microsoft.mrtk.graphicstools.unity/Runtime/Shaders/GraphicsToolsStandardProgram.hlsl(473) (on d3d11)
````

I will try to learn and try some more.　Please wait a little longer!

**Comment by Cameron-Micka** [comment]
Nice progress! Your code looks correct to me. 

Maybe the error is in the definition of the texture sampler? There are two places you need to define textures. The top is for URP and the bottom is for built-in:
![image](https://user-images.githubusercontent.com/13305729/174680815-66cc724d-abcc-4cfe-90a8-ce2ec5222b1b.png)

If you get stuck I'm happy to look at your branch too. 😊

**Comment by HoloMoto** [comment]
@Cameron-Micka 
I tried even more! 
https://github.com/HoloMoto/MixedReality-GraphicsTools-Unity/tree/holomoto/emissionmap
I can that the Shader functionality works fine, but when I enable only the EmissionMap I created this time without using other textures, the sampler definition in Input.hlsl does not compile and throws an error.

After further investigation, I found that if I comment out StandardShaderGUI.cs, the sampler definition works even if I use EmissionMap by itself.

if used textures,I expect that Sampler in input.hlsl is defined somewhere in  StandardShaderGUI.cs .
If my guess is correct, can you give me a hint?
I can do it in a little while ☺

**Comment by Cameron-Micka** [comment]
Is this the warning you are seeing @HoloMoto?
![image](https://user-images.githubusercontent.com/13305729/175607128-69e5c8d8-3fe2-488f-8da6-1b8458546569.png)

If so, you can fix it by changing your code to this:
![image](https://user-images.githubusercontent.com/13305729/175607190-5b951010-36c6-45d1-9228-4d6004fe0338.png)

`SAMPLE_TEXTURE2D` and `tex2D` return a 4-component color. This change tells the compiler you only care about the first 3 components since you are assigning to a 3-component color.

**Comment by HoloMoto** [comment]
Thank you.
The points you comented were indeed not addressed and have been corrected.

Apart from that, there is a problem with the UVs going wrong when using EmissionMap.
　This causes EmissionMap sampling to go wrong and also causes it to be Unlit.

　This problem can be resolved by using other texture functions or by commenting out StandardShaderGUI.cs, so perhaps input.uv or normal is broken.

　I thought StandardShaderGUI.cs was managing the display of the properties on the inspector, but is there any process in StandardShaderGUI.cs that controls normal or uv?


https://www.youtube.com/watch?v=Vaw7S5ayOQQ

**Comment by Cameron-Micka** [comment]
Thanks for the video! That was helpful in understanding the issue. 

I'll check out your PR now and leave any feedback. 😊

**Comment by HoloMoto** [comment]
@Cameron-Micka 
Thanks for merging our suggestions. Thanks again for your support.
Now that you have merged, I am closing this issue!
I am also proposing a sample of this feature in #47  I will work on this one as well.
