### ISSUE TITLE
MeshOutline only outline part of mesh for multi-material mesh

### ISSUE THREAD

**Issue by Ethan-Zhu-code** [microsoft/MixedReality-GraphicsTools-Unity#192]
## Describe the bug

MeshOutline component only works on part of mesh, when the mesh has multiple materials.

## To reproduce

1. Create a mesh with multiple material, import it to Unity
2. Drag the model into a scene
3. Add MeshOutline component to the created GameObject
4. Apply highlight material to the inspector Outline Material slot
5. Click Play button

## Expected behavior

The outline effect should applied to the whole mesh.

## Screenshots

![error1](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/79aabeb5-c1e8-4e1d-bb1f-e5e89cd70e80)

For my case, I created a hammer model and assign two materials to the mesh, for wood and iron part respectively.

![originalmaterial0](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/d102e828-4367-45a8-ae96-11691cb07df5)

![originalmaterial1](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/84d01f7d-c7d1-4389-a414-887052a6531f)

By clicking the applied outline material, it shows the outline material only works on the front iron part.

![appliedmaterial](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/384e8c2b-749b-4bdd-81b3-1f3bc5432f6f)

Setup for the MeshOutline component and model import

![Inspector](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/bea72cd6-5f49-4cc9-925e-0fc5a016f846)

![ImportSetup1](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/546757b3-c1fb-4448-9b31-45b149e1a85e)

![ImportSetup2](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/f508b5fc-8965-4eaa-811a-3a31602a3b8b)

## Your setup (please complete the following information)

- Unity Version 2021.3.26f1c1
- Graphics Tools Version v0.6.2

## Target platform (please complete the following information)

Unity Editor targeted to UWP platform for Hololens 2

**Comment by Cameron-Micka** [comment]
Thank you @Ethan-Zhu-code for this great bug report. We will take a look at fixing this. 😊
