### ISSUE TITLE
StandardShader's NormalMapScale property doesn't work in Built-in rendering pipeline

### ISSUE THREAD

**Issue by Ethan-Zhu-code** [microsoft/MixedReality-GraphicsTools-Unity#194]
## Describe the bug

When using built-in rendering pipeline, NormalMapScale property doesn't work in MixedReality GraphicTools Standard/StandardCanvas shader.

## To reproduce

1. Create a new Unity project using built-in rendering pipeline
2. Import MRTK3 and Graphic-Tools package via MixedReality Tool
3. Create a GraphicTools Standard material.
4. Assign a normal map to the material.
5. Assign the material to a gameobject with meshrenderer.
6. Change the NormalMapScale property.

## Expected behavior

The bump effect should change according to the NormalMapScale.

## Screenshots

The sculpting effect is based on the normal map, change value of NormalMapScale property make no difference to the appearance.

![screenshot_1](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/57004245-8d34-4fda-bf73-d897fbad39f3)
![screenshot_2](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/c0ee067f-8278-4b2c-8c48-6929bba4b177)
![screenshot_3](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/0d1253ef-25fb-42ee-85dd-17ebf993d96c)

After unchecking EnableNormalMap, the sculpting effect disappear.

![screenshot_4](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/51185278/23fc93db-cd79-440a-a1dd-271b427f32b0)

## Your setup

- Unity 2021.3.26f1c1 w. Graphics Tools 0.6.2
- Unity 2021.3.22f1c1 w. Graphics Tools 0.5.14

## Target platform

- HoloLens 2

**Comment by Ethan-Zhu-code** [comment]
Seems a duplicate issue. [Normal map scaling doesn't work in standard shader](https://github.com/microsoft/MixedRealityToolkit-Unity/issues/8819#issue-725665151)

**Comment by Cameron-Micka** [comment]
Thanks for reporting this @Ethan-Zhu-code - this certainly looks like a bug. We will investigate!

**Comment by palmerdesigns** [comment]
Hey Ethan! Just getting around to looking at this issue. For some reason I'm noticing both the `GraphicTools Standard Shader` and `GraphicsTools Standard/StandardCanvas Shader` appear to be working when I adjust the `NormalMapScale `property.

However I'm running:
- Unity 2021.3.16f1
- MRTK Graphics Tools 0.6.2
- Built-In Rendering Pipeline
