### ISSUE TITLE
Error in Acrylic Render Pass

### ISSUE THREAD

**Issue by mgrubert-ml** [microsoft/MixedReality-GraphicsTools-Unity#196]
## Describe the bug

Error due to AcrylicBlur shader in Unity 2023.1.x :
Library\PackageCache\com.microsoft.mrtk.graphicstools.unity@cd59e032bb2e\Runtime\Experimental\Acrylic\Scripts\AcrylicBlurRenderPass.cs(189,13): error CS0619: 'ScriptableRenderPass.ConfigureTarget(RenderTargetIdentifier)' is obsolete: 'Use RTHandle for colorAttachment'

## To reproduce

Create URP project in Unity 2023.1.14f1, then used MRTK tool to import Graphicstools and try to open project.

## Your setup (please complete the following information)

- Unity Version 2023.1.14f1
- 0.5 and 0.61

## Target platform (please complete the following information)

- Standalone PC
- Android

**Comment by Cameron-Micka** [comment]
Thanks @mgrubert-ml - we will take a look at this. We don't yet support Unity 2023. But will eventually and address this.

**Comment by mgrubert-ml** [comment]
@Cameron-Micka The Readme.MD says 
"The Graphics Tools package requires Unity 2021.3 and above."
Might be helpful to put an upper bound there as well (Unity 2021.3 thru Unity 2022.x)

**Comment by Cameron-Micka** [comment]
Great idea @mgrubert-ml!

**Comment by Torgo13** [comment]
I was able to update it to the new API by following this guide: [https://forum.unity.com/threads/rendertargethandle-is-obsolete-deprecated-in-favor-of-rthandle.1211052/#post-7737570](url)

**Comment by Cameron-Micka** [comment]
That's a wonderful resource, thanks @Torgo13. If you are able to make a PR with your changes, I would be happy to review it as well. 😊

**Comment by Cameron-Micka** [comment]
Hey @mgrubert-ml, this should be fixed now with v0.7.0 and above.
