### ISSUE TITLE
RenderTargetHandle deprecated in Unity 2023

### ISSUE THREAD

**Issue by marlenaklein-msft** [microsoft/MixedReality-GraphicsTools-Unity#210]
## Describe the bug

RenderTargetHandle is deprecated in favor of RTHandle.

## To reproduce

Load a project with graphics tools v0.6.5 or v.0.6.7 on Unity 2023.2 LTS. Observe compile errors. 

## Screenshots

![image](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/125413876/8427a773-6cde-4641-8cda-c402d0bbc013)

## Your setup (please complete the following information)

- Unity 2023.2.17f1
- Graphics Tools v0.6.7 or v0.6.5

**Comment by Cameron-Micka** [comment]
Hey @marlenaklein-msft, this should be fixed now with v0.7.0 and above.
