### ISSUE TITLE
GraphicsToolsTextMesh pro visual artifacts in Unity 2023.2.17f1

### ISSUE THREAD

**Issue by holomatt** [microsoft/MixedReality-GraphicsTools-Unity#211]
## Describe the bug

Text using this shader shows underlines in URP using 2023.2.17f1 (see screenshot)

## To reproduce

Apply the shader to TMP UGUI text in 2023.2.17f1 Canvas screenspace overlay or world space. Observe artifacts.

## Expected behavior

No artifacts 

## Screenshots

![image](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/12565843/96a28766-4e3b-4a03-bc94-1a0493b431ed)

## Your setup (please complete the following information)

Unity 2023.2.17f1 and MRGT 0.6.9
## Target platform (please complete the following information)

Standalone and UWP HL2

**Comment by anonymous2585** [comment]
I have the same issue with Unity 2023.2.20f1 and MRGT 0.7.0 and a linear color space.

**Comment by Cameron-Micka** [comment]
Thanks! My goal is to fix this next week.

**Comment by Cameron-Micka** [comment]
This has now been fixed in [v0.7.1](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/releases/tag/v0.7.1)!
