### ISSUE TITLE
Regarding the lack of support for the Acrylic feature in Unity 6

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedReality-GraphicsTools-Unity#217]
## Describe the bug

I was investigating the use of MRGT in Unity6. (I'm trying to combine this with my Unity6 studies since I haven't been exposed to it lately!)
The import and shader functions themselves seem to be usable from what I can see, but in the acrylic functionality, the RenderTarget Handle class is deprecated in Unity6 and replaced by the RTHandle system.
Currently the AcrylicBlurRenderPass class uses the RenderTargetHandle class like RenderTargetHandle target1, but it needs to be replaced with the RTHandle system.

This causes the following error when importing in Unity6

>Library\PackageCache\com.microsoft.mrtk.graphicstools.unity\Runtime\Experimental\Acrylic\Scripts\AcrylicBlurRenderPass.cs(179,52): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

>rary\PackageCache\com.microsoft.mrtk.graphicstools.unity\Runtime\Experimental\Acrylic\Scripts\AcrylicBlurRenderPass.cs(20,17): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

>Library\PackageCache\com.microsoft.mrtk.graphicstools.unity\Runtime\Experimental\Acrylic\Scripts\AcrylicBlurRenderPass.cs(21,17): error CS0619: 'RenderTargetHandle' is obsolete: 'Deprecated in favor of RTHandle'

## To reproduce

For now, I am able to use it normally by deleting the acrylic folder.(-"-)
This wonderful MRGT project should continue to be usable in Unity 6! (I WANT TO USE!!!!!!!)

## Screenshots

![image](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/assets/36409613/633e9b28-d545-4213-a20a-1c0e9dd3fbae)

## Your setup (please complete the following information)

- Unity Version 6000.0.2f1 (UniversalRP template)
- Graphics Tools Version (leatest git hub branch version (main))

## Target platform (please complete the following information)

- Unity6 Editor

## Reference Info

https://forum.unity.com/threads/rendertargethandle-is-obsolete-deprecated-in-favor-of-rthandle.1211052/

https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@13.1/manual/upgrade-guide-2022-1.html

**Comment by Cameron-Micka** [comment]
Good to hear from you @HoloMoto! If you use [Graphics Tools v0.7.1](https://github.com/microsoft/MixedReality-GraphicsTools-Unity/releases/tag/v0.7.1)+ does the issue go away? It should have been fixed in https://github.com/microsoft/MixedReality-GraphicsTools-Unity/pull/212

**Comment by Cameron-Micka** [comment]
Marking as closed since this is fixed in v0.7.1.
