### ISSUE TITLE
Apply transparency to colored mesh

### ISSUE THREAD

**Issue by mnamvarcfd** [microsoft/MixedReality-GraphicsTools-Unity#228]
I am working to develop an AR app on HoloLens 2 using MRTK3 and Unity. The goal is to apply **color** to each vertex of a mesh and also apply **transparency**. I use Graphics Tools/Standard. However, I could apply color to the mesh's vertices, not transparency.

Is there any capability in MRTK to achieve this goal?

**Comment by Cameron-Micka** [comment]
Hi @mnamvarcfd, thank you for reaching out. Is the issue the alpha value in your mesh's vertex colors isn't being applied? If so, do you have a mesh with vertex colors with alpha values I could test?

I tried with another Mesh in Graphics Tools that has vertex colors - but I think the alpha values are all 1.0:
![Image](https://github.com/user-attachments/assets/2fb923dd-41c3-4b0c-b210-cf00b6632636)

The material setup to be transparent and display vertex colors:
![Image](https://github.com/user-attachments/assets/0a8f3803-b8f1-4da6-8a6f-16bf057d5ccd)

**Comment by mnamvarcfd** [comment]
Hi @Cameron-Micka 

Yes, the problem is the transparency. However, I applied 0.1 for the alpha value.
For debuging purposes, I used a triangle and applied blue, red, and green colors to each vertex. For the material I am using the same material as you used (i.e. `Graphics Tools/Standard`), rendering mode: `Transparent`, and also, check the `Vertex colors`. The code I am using for debugging is as follows:

```
using UnityEngine;

public class MeshVisualizerDebug : MonoBehaviour
{
    [SerializeField] private Material debugMaterial;

    private Mesh mesh;
    private GameObject meshObj;

    private void Start()
    {
        // Initialize GameObject
        meshObj = new GameObject("DebugMeshObj");

        // Assign material
        Material material = debugMaterial;

        // Set up MeshFilter and MeshRenderer
        var meshFilter = meshObj.AddComponent<MeshFilter>();
        mesh = new Mesh();
        meshFilter.mesh = mesh;

        var renderer = meshObj.AddComponent<MeshRenderer>();
        renderer.material = material;

        // Directly define the mesh data
        Vector3[] vertices = new Vector3[]
        {
            new Vector3(0.0f, 0.0f, 0.0f),
            new Vector3(1.0f, 0.0f, 0.0f),
            new Vector3(0.0f, 1.0f, 0.0f)
        };

        int[] triangles = new int[]
        {
            0, 1, 2
        };

        Color[] colors = new Color[]
        {
            new Color(0.0f, 0.0f, 1.0f, 0.1f), // Blue with 0.1 alpha
            new Color(1.0f, 0.0f, 0.0f, 0.1f), // Red with 0.1 alpha
            new Color(0.0f, 1.0f, 0.0f, 0.1f)  // Green with 0.1 alpha
        };

        // Apply the mesh data
        ApplyMesh(vertices, triangles, colors);
    }

    private void ApplyMesh(Vector3[] vertices, int[] triangles, Color[] colors)
    {
        // Apply data to the mesh
        mesh.Clear();
        mesh.vertices = vertices;
        mesh.triangles = triangles;
        mesh.colors = colors;

        // Recalculate properties
        mesh.RecalculateBounds();
        mesh.RecalculateNormals();
    }
}
```

**Comment by Cameron-Micka** [comment]
Thank you so much for the sample code @mnamvarcfd! I'll work on fixing this.

**Comment by Cameron-Micka** [comment]
Hey @mnamvarcfd, I just tried your script and it looks like the alpha value of the vertex is coming though correctly: 
![Image](https://github.com/user-attachments/assets/7389ea05-d64e-4378-ae0c-98d17acf6ce3)

Are you seeing a different behavior?

**Comment by mnamvarcfd** [comment]
Hi @Cameron-Micka 

Thanks for your response. 

In the unity scene it is ok, but not on the HoloLens 2 device. 
I read more about the shader parameters and I played with them. With the setting I did in the following picture it is working fine and I can see the transparency, but it is too sensitive to the amount of light in the physical space. 

![Image](https://github.com/user-attachments/assets/a5c23c7f-c595-4f51-9622-5c2a5c820948)

**Comment by Cameron-Micka** [comment]
Ah gotcha, if it's too sensitive to the amount of light in the physical space - what happens if you bring the albedo color down a bit. For example, make it neutral grey (0.5, 0.5, 0.5, 1.0) rather than white?

**Comment by mnamvarcfd** [comment]
If I use grey for albedo the color is changed compared to the white. However, the white value for albedo results in a more realistic color map.

BTW if you confirm the above setup is correct I go on that. 


![Image](https://github.com/user-attachments/assets/fa6198dc-bd0a-48ef-93e1-08ca170189b3)

albedo: Grey

![Image](https://github.com/user-attachments/assets/eed29d07-5c73-4d54-96aa-dfe2f5ffdfc0)

albedo: white

**Comment by Cameron-Micka** [comment]
Your images look correct to me. But if you are unhappy with the result, I'd recommend experimenting with these material values:
![Image](https://github.com/user-attachments/assets/3a5afd32-1ae8-49b8-b99a-42a0fd1a7831)

Here are docs on those values: https://docs.unity3d.com/Manual/SL-Blend.html

You may be able to land on the blending result you desire!
