### ISSUE TITLE
Place a sample into the Materialgallery that demonstrates the functionality of the EmissionMap implemented in #35.

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedReality-GraphicsTools-Unity#47]
## Describe the problem

I proposed and implemented EmissionMap as a new feature of MRGTStandardShader in #35 .
　I want to place this new feature's sample in MaterialGallery sample scene, where MRGTStandardShader's features are collected as samples.

**Comment by Cameron-Micka** [comment]
Great idea! @Species521 can help with modifying samples.

**Comment by Species521** [comment]
PR#69 is referring to this issue.
https://github.com/microsoft/MixedReality-GraphicsTools-Unity/pull/69

**Comment by Cameron-Micka** [comment]
Closed with #69
