### ISSUE TITLE
MeshOutline is hard-coded to only work with MeshRenderers

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedReality-GraphicsTools-Unity#7]
## Describe the bug

`MeshOutline` only works with MeshRenderers, when it doesn't have to. It also works with `SkinnedMeshRenderer`s (and I presume other types of generic `Renderer`s!)

## To reproduce

Attempt to add `MeshOutline` to a skinned mesh.

## Expected behavior

Ideally you should be able to use `MeshOutline` on skinned meshes. I tested with a local fork and it seems fine to replace `MeshRenderer` with `Renderer`.

## Your setup (please complete the following information)

- Unity 2020.3.30f1
- Graphics Tools 0.3.0

**Comment by Cameron-Micka** [comment]
Thank you for the bug report @Zee2! This is definitely something we need to address.
