### ISSUE TITLE
Aliasing and artifacts with independent round corners and automatic edge smoothing

### ISSUE THREAD

**Issue by Cameron-Micka** [microsoft/MixedReality-GraphicsTools-Unity#74]
## Describe the bug

Graphics Tools/Standard shader materials with independent round corners and automatic edge smoothing exhibit aliasing artifacts: 

![image](https://user-images.githubusercontent.com/13305729/179098780-d2e4388a-d5e7-467e-a855-2a441af50eee.png)

## To reproduce

1. Create a new material using the Graphics Tools/Standard or Graphics Tools/Standard Canvas shader
2. Enable Round Corners
3. Enable Independent Corners
4. Ensure Edge Smoothing Mode is set to automatic
5. Set one corner to be a different value than the other coroners (example 0, 3, 3, 3)

## Expected behavior

No aliasing on edges and artifact line though center.

## Screenshots

![image](https://user-images.githubusercontent.com/13305729/179099316-4b6fd3b9-15f7-4490-baa2-6a6e3a6e9397.png)

## Your setup

- Unity Version [e.g. 2020.3.6f1]
- Graphics Tools Version [e.g. v0.4.8]

## Target platform

- Editor

## Additional context

n/a

**Comment by Zee2** [comment]
I'm repro-ing this on the RoundedRectMask @Cameron-Micka. When the rect mask has independent corners, the same artifacts appear. This is going to be a relatively big issue for $internalProject. Would appreciate this getting fixed sooner rather than later! It's a super handy feature :)

**Comment by Cameron-Micka** [comment]
That's good to know, thanks @Zee2!
