### ISSUE TITLE
MeshOutline that works with depth sorting

### ISSUE THREAD

**Issue by Zee2** [microsoft/MixedReality-GraphicsTools-Unity#8]
## Describe the problem

It would be really neat to be able to use properly sorted depth with a mesh outline, in order to render hands using a nice outline, like so:

![image](https://user-images.githubusercontent.com/5544935/172305305-3bcefbc5-0b28-47aa-ad79-eebbf13ee1cf.png)

However, it gets wonky when other objects are involved:

![image](https://user-images.githubusercontent.com/5544935/172305376-fc690e5a-cff2-4617-9bba-d456fb7b7298.png)

## Describe the solution you'd like

Out-of-the-box support for mesh outlines that respect depth.

## Describe alternatives you've considered

A depth pre-pass/multi-pass shader should be able to do this.

**Comment by Cameron-Micka** [comment]
You might be able to solve the issue in the bottom screenshot by rendering the hand at the end of the frame (in the [overlay ](https://docs.unity3d.com/ScriptReference/Rendering.RenderQueue.Overlay.html) queue or manually with a URP [render object feature](https://docs.unity3d.com/Packages/com.unity.render-pipelines.universal@10.1/manual/urp-renderer-feature.html#:~:text=A%20Renderer%20Feature%20is%20an,Renderer%20Feature%20called%20Render%20Objects.)). 

But I agree this should work better out-of-the-box. We'll see if we can come up with a solution!

**Comment by Cameron-Micka** [comment]
Related issue: https://github.com/microsoft/MixedRealityToolkit-Unity/issues/9630

**Comment by Cameron-Micka** [comment]
![image](https://user-images.githubusercontent.com/13305729/197835766-523ebccf-e2f3-44e0-b38f-03809f4cc348.png)

**Comment by Cameron-Micka** [comment]
Current plan is to add a checkbox to the inspector to automatically enable stencil based workflows.

**Comment by NorbertNemec** [comment]
To mention one important architectural requirement as discussed:

The solution should work without restricting the design of the scene, specifically it should not add requirements to 
the materials used in the scene.

One way to achieve this may to move the stencil testing functionality shown in the above screenshot on left-hand side (on Gray material) could be moved to a tertiary invisible materials, added by MeshOutline. The primary material of the body could then be untouched whatever it may be.

**Comment by Cameron-Micka** [comment]
Totally agree @NorbertNemec, we'll make sure to add an option for a third material in charge of stencil writing.
