### ISSUE TITLE
HoverLightInspector.cs creates duplicate menu item with warnings when MRTK 2 assets are still in the project

### ISSUE THREAD

**Issue by DenisTschitschenkow** [microsoft/MixedReality-GraphicsTools-Unity#82]
## Describe the bug

Unity shows a warning about duplicate Menu Items for HoverLight "GameObject/Light/Hover Light".

This happens when the MRTK 2.X Implementation is still in the project for a smooth transition into MRTK3 in the future.

A Solutions might be to just Rename the Menu Item in Graphics Tools in HoverLightInspector.cs 

 [MenuItem("GameObject/Light/GraphicsTools/Hover Light")]

![image](https://user-images.githubusercontent.com/28431626/180776882-699c9970-216a-496f-8e23-aff55440cd3a.png)

## To reproduce

1.) Load MRTK 2.7 Core Assets with the HoverLight Script
2.) Load GraphicsTools Package in the Project.
3.) Unity Editor shows warnings about duplicate Menu Items. "Cannot add menu item 'GameObject/Light/Hover Light' for method 'HoverLightInspector.CreateHoverLight' because a menu item with the same name already exists."

## Expected behavior

No Warnings shown for clean Editor Setup

## Your setup (please complete the following information)

- Unity Version 2021.3.31f1
- Graphics Tools Version  v0.4.0

## Target platform (please complete the following information)

- Unity Editor
## Additional context

This minor issue is to be solved for a smooth transition between the major MRTK implementations.

**Comment by Cameron-Micka** [comment]
Thank you @DenisTschitschenkow for reporting this issue and suggesting a fix! I've made a PR to address this: https://github.com/microsoft/MixedReality-GraphicsTools-Unity/pull/83
