### ISSUE TITLE
An additional Editor folder is created if one already exists but MeasureToolSettings.asset doesn't

### ISSUE THREAD

**Issue by keveleigh** [microsoft/MixedReality-GraphicsTools-Unity#95]
## Describe the bug

If an Editor folder exists, the `GetOrCreateSettings()` path for MeasureToolSettings.asset will create a second one, but still place the new asset in the correct, original folder.

It seems to all come down to this line:

https://github.com/microsoft/MixedReality-GraphicsTools-Unity/blob/64ce5bbee6cc3872c0a00dc5db4cc05b56fae806/com.microsoft.mrtk.graphicstools.unity/Editor/MeasureTool/MeasureToolSettings.cs#L84

Unity seems to get confused by the trailing `/`...

## Screenshots

![image](https://user-images.githubusercontent.com/3580640/187312374-5a10f100-ce86-4dea-97f2-91e0221e0f91.png)

## Your setup (please complete the following information)

- Unity Version 2020.3.38
- Graphics Tools Version 0.4.0

**Comment by Cameron-Micka** [comment]
@breezinstein do you have time to look at this one?

**Comment by keveleigh** [comment]
> @breezinstein do you have time to look at this one?

Oops, I missed this and went ahead and opened #96 😬

**Comment by Cameron-Micka** [comment]
No, thank you, that was quick! @breezinstein I merged @keveleigh's PR. Feel free to update if need be.
