### ISSUE TITLE
Need shortcut key to make the screenshot taking function easier to handle while wearing the HMD.

### ISSUE THREAD

**Issue by HoloMoto** [microsoft/MixedReality-GraphicsTools-Unity#99]
## Describe the problem

The screen capture features offered by MRGT are very attractive, including background hollowing and up to 4x resolution.

However, it has no shortcut compared to the standard Windows PC screenshot ([Ctrl]+[Windows]+[S]) and, as far as I know, must be selected from the Unity menu, and I feel that this single point makes a big difference in ease of use.

　Especially while using PCVR or HoloLens HolographicRemoting and wearing a HMD, it is sometimes difficult to move the cursor and select from the menu every time.

　I have been discussing this problem with my colleagues, and I feel the need for a shortcut key.

## Describe the solution you'd like

If a shortcut key could be used to take a capture while wearing the HMD and specifying a fine angle of view during execution, more users would prefer to use MRGT screenshots.

## Describe alternatives you've considered

Developer enable screen capture by Shortcut keys.

It should be noted, however, that the keys will overlap with other MRTK functions and general shortcut keys.

**Comment by Cameron-Micka** [comment]
This is a great suggestion! Please feel free to add shortcuts or we can assign to someone. 😊

**Comment by HoloMoto** [comment]
@Cameron-Micka  Thank you!
I`ll try!!
　How are MRTG and other MRTK packages implemented?
　It looks like the shortcut manager can be used since Unity2019.
　If I implement it, should I use the shortcut manager in terms of avoiding shortcut conflicts with other packages used by users?

**Comment by Cameron-Micka** [comment]
MRTKv3 and MRGT use Unity 2020 and above. So, you should be good to use the shortcut manager. 

Let me also add @keveleigh in case he has some insights on how shortcut conflicts are avoided across MRTKv3.

**Comment by HoloMoto** [comment]
Thank you! @Cameron-Micka  and @keveleigh  
I'll implement it at shortcut manager!
Just this past holiday I touched and learned shortcut manager, so I should be able to do it!

At this point I am considering two methods.
(1) It is provided as a shortcut from the beginning, like many other MRTK functions, and developers can use it right away.
(2) Shortcut keys are not enabled by default, and users who want to use screenshots can go to the Window→GraphicsTools→Take screenshots menu and select "Enable capture by shortcut keys" (temp name). Select "Take screenshots" from the Window→GraphicsTools→Take screenshots menu, and enable capturing with shortcut keys.

Which method is more user-friendly?

**Comment by Cameron-Micka** [comment]
I reached out to the rest of the MRTK team and we don't have an established pattern yet. But, using the shortcut manager seems like the ideal and recommended path forward. This [attribute](https://docs.unity3d.com/2019.1/Documentation/ScriptReference/ShortcutManagement.ShortcutAttribute.html) might be helpful too?
